version: '3.8'

services:
  postgres:
    image: library/postgres:12-alpine
    container_name: postgres_app_urnode
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - Docker/.env

  # Redis - result backend
  redis:
    container_name: redis_app_urnode
    image: redis:alpine
    hostname: redis

  backend:
    container_name: backend_app_urnode
    expose:
      - "8000"
    image: "ghcr.io/argusoss/urnode-backend:latest"
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./urNode-backend:/app
    env_file:
      - Docker/.env
    links:
      - celery
      - rabbit
      - postgres
      - redis

  celery:
    image: "ghcr.io/argusoss/urnode-celery-backend:latest"
    container_name: celery_server
    volumes:
      - "./urNode-backend:/app"
    env_file:
      - Docker/.env
    depends_on:
      - redis
      - postgres
    links:
      - postgres
      - rabbit
      - redis

  rabbit:
    hostname: rabbit
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
