apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chaindata-gethnode
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: ebs-gp3
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chaindata-prysm
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: ebs-gp3
  accessModes:
    - ReadWriteOnce
