name: Build and publish Docker image to ghcr.io
on:
  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [published]

  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches:
      - main
      - master
#    paths:
#      - "urNode-backend/**"
  # allow manual triggers
  workflow_dispatch:

jobs:
  docker_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # https://github.community/t/github-actions-repository-name-must-be-lowercase/184924
      - name: downcase REPO
        run: |
          echo "REPO_LC=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      # https://github.com/marketplace/actions/push-to-ghcr
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${REPO_LC}-backend
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # optionally push to the Docker Hub (docker.io)
          # docker_io_token: ${{ secrets.DOCKER_IO_ACCESS_TOKEN }}  # see https://hub.docker.com/settings/security